# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EyeCareV1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
try:

    import Tkinter as tk

except:

    import tkinter as tk


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1123, 842)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(880, 790, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 710, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(880, 750, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(680, 150, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(680, 200, 73, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(680, 250, 73, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(680, 300, 73, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setGeometry(QtCore.QRect(680, 340, 73, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setGeometry(QtCore.QRect(680, 380, 73, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        self.comboBox_7.setGeometry(QtCore.QRect(680, 420, 73, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(Form)
        self.comboBox_8.setGeometry(QtCore.QRect(680, 460, 73, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(Form)
        self.comboBox_9.setGeometry(QtCore.QRect(680, 510, 73, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(Form)
        self.comboBox_10.setGeometry(QtCore.QRect(680, 550, 73, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_11 = QtWidgets.QComboBox(Form)
        self.comboBox_11.setGeometry(QtCore.QRect(680, 610, 73, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(Form)
        self.comboBox_12.setGeometry(QtCore.QRect(680, 660, 73, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_13 = QtWidgets.QComboBox(Form)
        self.comboBox_13.setGeometry(QtCore.QRect(680, 700, 73, 22))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_14 = QtWidgets.QComboBox(Form)
        self.comboBox_14.setGeometry(QtCore.QRect(680, 740, 73, 22))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.verticalScrollBar = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar.setGeometry(QtCore.QRect(1110, 0, 16, 841))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "EYE CARE"))
        self.pushButton.setText(_translate("Form", "PushButton"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.comboBox.setItemText(0, _translate("Form", "0"))
        self.comboBox.setItemText(1, _translate("Form", "1"))
        self.comboBox.setItemText(2, _translate("Form", "2"))
        self.comboBox.setItemText(3, _translate("Form", "3"))
        self.comboBox.setItemText(4, _translate("Form", "4"))
        self.comboBox_2.setItemText(0, _translate("Form", "0"))
        self.comboBox_2.setItemText(1, _translate("Form", "1"))
        self.comboBox_2.setItemText(2, _translate("Form", "2"))
        self.comboBox_2.setItemText(3, _translate("Form", "3"))
        self.comboBox_2.setItemText(4, _translate("Form", "4"))
        self.comboBox_3.setItemText(0, _translate("Form", "0"))
        self.comboBox_3.setItemText(1, _translate("Form", "1"))
        self.comboBox_3.setItemText(2, _translate("Form", "2"))
        self.comboBox_3.setItemText(3, _translate("Form", "3"))
        self.comboBox_3.setItemText(4, _translate("Form", "4"))
        self.comboBox_4.setItemText(0, _translate("Form", "0"))
        self.comboBox_4.setItemText(1, _translate("Form", "1"))
        self.comboBox_4.setItemText(2, _translate("Form", "2"))
        self.comboBox_4.setItemText(3, _translate("Form", "3"))
        self.comboBox_4.setItemText(4, _translate("Form", "4"))
        self.comboBox_5.setItemText(0, _translate("Form", "0"))
        self.comboBox_5.setItemText(1, _translate("Form", "1"))
        self.comboBox_5.setItemText(2, _translate("Form", "2"))
        self.comboBox_5.setItemText(3, _translate("Form", "3"))
        self.comboBox_5.setItemText(4, _translate("Form", "4"))
        self.comboBox_6.setItemText(0, _translate("Form", "0"))
        self.comboBox_6.setItemText(1, _translate("Form", "1"))
        self.comboBox_6.setItemText(2, _translate("Form", "2"))
        self.comboBox_6.setItemText(3, _translate("Form", "3"))
        self.comboBox_6.setItemText(4, _translate("Form", "4"))
        self.comboBox_7.setItemText(0, _translate("Form", "0"))
        self.comboBox_7.setItemText(1, _translate("Form", "1"))
        self.comboBox_7.setItemText(2, _translate("Form", "2"))
        self.comboBox_7.setItemText(3, _translate("Form", "3"))
        self.comboBox_7.setItemText(4, _translate("Form", "4"))
        self.comboBox_8.setItemText(0, _translate("Form", "0"))
        self.comboBox_8.setItemText(1, _translate("Form", "1"))
        self.comboBox_8.setItemText(2, _translate("Form", "2"))
        self.comboBox_8.setItemText(3, _translate("Form", "3"))
        self.comboBox_8.setItemText(4, _translate("Form", "4"))
        self.comboBox_9.setItemText(0, _translate("Form", "0"))
        self.comboBox_9.setItemText(1, _translate("Form", "1"))
        self.comboBox_9.setItemText(2, _translate("Form", "2"))
        self.comboBox_9.setItemText(3, _translate("Form", "3"))
        self.comboBox_9.setItemText(4, _translate("Form", "4"))
        self.comboBox_10.setItemText(0, _translate("Form", "0"))
        self.comboBox_10.setItemText(1, _translate("Form", "1"))
        self.comboBox_10.setItemText(2, _translate("Form", "2"))
        self.comboBox_10.setItemText(3, _translate("Form", "3"))
        self.comboBox_10.setItemText(4, _translate("Form", "4"))
        self.comboBox_11.setItemText(0, _translate("Form", "0"))
        self.comboBox_11.setItemText(1, _translate("Form", "1"))
        self.comboBox_11.setItemText(2, _translate("Form", "2"))
        self.comboBox_11.setItemText(3, _translate("Form", "3"))
        self.comboBox_11.setItemText(4, _translate("Form", "4"))
        self.comboBox_12.setItemText(0, _translate("Form", "0"))
        self.comboBox_12.setItemText(1, _translate("Form", "1"))
        self.comboBox_12.setItemText(2, _translate("Form", "2"))
        self.comboBox_12.setItemText(3, _translate("Form", "3"))
        self.comboBox_12.setItemText(4, _translate("Form", "4"))
        self.comboBox_13.setItemText(0, _translate("Form", "0"))
        self.comboBox_13.setItemText(1, _translate("Form", "1"))
        self.comboBox_13.setItemText(2, _translate("Form", "2"))
        self.comboBox_13.setItemText(3, _translate("Form", "3"))
        self.comboBox_13.setItemText(4, _translate("Form", "4"))
        self.comboBox_14.setItemText(0, _translate("Form", "0"))
        self.comboBox_14.setItemText(1, _translate("Form", "1"))
        self.comboBox_14.setItemText(2, _translate("Form", "2"))
        self.comboBox_14.setItemText(3, _translate("Form", "3"))
        self.comboBox_14.setItemText(4, _translate("Form", "4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
