# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EyeCareV1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1559, 977)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1420, 470, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(680, 230, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(680, 270, 73, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(680, 310, 73, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(680, 350, 73, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(Form)
        self.comboBox_5.setGeometry(QtCore.QRect(680, 390, 73, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(Form)
        self.comboBox_6.setGeometry(QtCore.QRect(680, 430, 73, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(Form)
        self.comboBox_7.setGeometry(QtCore.QRect(680, 470, 73, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(Form)
        self.comboBox_8.setGeometry(QtCore.QRect(680, 510, 73, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(Form)
        self.comboBox_9.setGeometry(QtCore.QRect(680, 550, 73, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(Form)
        self.comboBox_10.setGeometry(QtCore.QRect(680, 590, 73, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_11 = QtWidgets.QComboBox(Form)
        self.comboBox_11.setGeometry(QtCore.QRect(680, 770, 73, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(Form)
        self.comboBox_12.setGeometry(QtCore.QRect(680, 810, 73, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_13 = QtWidgets.QComboBox(Form)
        self.comboBox_13.setGeometry(QtCore.QRect(680, 850, 73, 22))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_14 = QtWidgets.QComboBox(Form)
        self.comboBox_14.setGeometry(QtCore.QRect(680, 890, 73, 22))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 230, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 260, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 300, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(530, 350, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(590, 390, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(590, 430, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(570, 470, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(580, 510, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(550, 550, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(490, 580, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(460, 760, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(420, 800, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(370, 850, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(490, 880, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(50, 100, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(100, 140, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(40, 650, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(100, 680, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(100, 190, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(140, 720, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(880, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(880, 150, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(920, 150, 201, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(1140, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(1220, 150, 191, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(880, 195, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.comboBox_15 = QtWidgets.QComboBox(Form)
        self.comboBox_15.setGeometry(QtCore.QRect(930, 200, 73, 22))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(1050, 190, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(1100, 190, 71, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(880, 255, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setGeometry(QtCore.QRect(1200, 250, 104, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(1310, 250, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Form)
        self.label_29.setGeometry(QtCore.QRect(880, 310, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.comboBox_16 = QtWidgets.QComboBox(Form)
        self.comboBox_16.setGeometry(QtCore.QRect(1290, 310, 201, 31))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.label_30 = QtWidgets.QLabel(Form)
        self.label_30.setGeometry(QtCore.QRect(880, 360, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.comboBox_17 = QtWidgets.QComboBox(Form)
        self.comboBox_17.setGeometry(QtCore.QRect(1290, 360, 73, 31))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.label_31 = QtWidgets.QLabel(Form)
        self.label_31.setGeometry(QtCore.QRect(880, 410, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.comboBox_18 = QtWidgets.QComboBox(Form)
        self.comboBox_18.setGeometry(QtCore.QRect(1050, 411, 73, 31))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1272, 470, 121, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_2.clicked.connect(QtCore.QCoreApplication.instance().quit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "EYE CARE"))
        self.pushButton.setText(_translate("Form", "Submid"))
        self.comboBox.setItemText(0, _translate("Form", "0"))
        self.comboBox.setItemText(1, _translate("Form", "1"))
        self.comboBox.setItemText(2, _translate("Form", "2"))
        self.comboBox.setItemText(3, _translate("Form", "3"))
        self.comboBox.setItemText(4, _translate("Form", "4"))
        self.comboBox_2.setItemText(0, _translate("Form", "0"))
        self.comboBox_2.setItemText(1, _translate("Form", "1"))
        self.comboBox_2.setItemText(2, _translate("Form", "2"))
        self.comboBox_2.setItemText(3, _translate("Form", "3"))
        self.comboBox_2.setItemText(4, _translate("Form", "4"))
        self.comboBox_3.setItemText(0, _translate("Form", "0"))
        self.comboBox_3.setItemText(1, _translate("Form", "1"))
        self.comboBox_3.setItemText(2, _translate("Form", "2"))
        self.comboBox_3.setItemText(3, _translate("Form", "3"))
        self.comboBox_3.setItemText(4, _translate("Form", "4"))
        self.comboBox_4.setItemText(0, _translate("Form", "0"))
        self.comboBox_4.setItemText(1, _translate("Form", "1"))
        self.comboBox_4.setItemText(2, _translate("Form", "2"))
        self.comboBox_4.setItemText(3, _translate("Form", "3"))
        self.comboBox_4.setItemText(4, _translate("Form", "4"))
        self.comboBox_5.setItemText(0, _translate("Form", "0"))
        self.comboBox_5.setItemText(1, _translate("Form", "1"))
        self.comboBox_5.setItemText(2, _translate("Form", "2"))
        self.comboBox_5.setItemText(3, _translate("Form", "3"))
        self.comboBox_5.setItemText(4, _translate("Form", "4"))
        self.comboBox_6.setItemText(0, _translate("Form", "0"))
        self.comboBox_6.setItemText(1, _translate("Form", "1"))
        self.comboBox_6.setItemText(2, _translate("Form", "2"))
        self.comboBox_6.setItemText(3, _translate("Form", "3"))
        self.comboBox_6.setItemText(4, _translate("Form", "4"))
        self.comboBox_7.setItemText(0, _translate("Form", "0"))
        self.comboBox_7.setItemText(1, _translate("Form", "1"))
        self.comboBox_7.setItemText(2, _translate("Form", "2"))
        self.comboBox_7.setItemText(3, _translate("Form", "3"))
        self.comboBox_7.setItemText(4, _translate("Form", "4"))
        self.comboBox_8.setItemText(0, _translate("Form", "0"))
        self.comboBox_8.setItemText(1, _translate("Form", "1"))
        self.comboBox_8.setItemText(2, _translate("Form", "2"))
        self.comboBox_8.setItemText(3, _translate("Form", "3"))
        self.comboBox_8.setItemText(4, _translate("Form", "4"))
        self.comboBox_9.setItemText(0, _translate("Form", "0"))
        self.comboBox_9.setItemText(1, _translate("Form", "1"))
        self.comboBox_9.setItemText(2, _translate("Form", "2"))
        self.comboBox_9.setItemText(3, _translate("Form", "3"))
        self.comboBox_9.setItemText(4, _translate("Form", "4"))
        self.comboBox_10.setItemText(0, _translate("Form", "0"))
        self.comboBox_10.setItemText(1, _translate("Form", "1"))
        self.comboBox_10.setItemText(2, _translate("Form", "2"))
        self.comboBox_10.setItemText(3, _translate("Form", "3"))
        self.comboBox_10.setItemText(4, _translate("Form", "4"))
        self.comboBox_11.setItemText(0, _translate("Form", "0"))
        self.comboBox_11.setItemText(1, _translate("Form", "1"))
        self.comboBox_11.setItemText(2, _translate("Form", "2"))
        self.comboBox_11.setItemText(3, _translate("Form", "3"))
        self.comboBox_11.setItemText(4, _translate("Form", "4"))
        self.comboBox_12.setItemText(0, _translate("Form", "0"))
        self.comboBox_12.setItemText(1, _translate("Form", "1"))
        self.comboBox_12.setItemText(2, _translate("Form", "2"))
        self.comboBox_12.setItemText(3, _translate("Form", "3"))
        self.comboBox_12.setItemText(4, _translate("Form", "4"))
        self.comboBox_13.setItemText(0, _translate("Form", "0"))
        self.comboBox_13.setItemText(1, _translate("Form", "1"))
        self.comboBox_13.setItemText(2, _translate("Form", "2"))
        self.comboBox_13.setItemText(3, _translate("Form", "3"))
        self.comboBox_13.setItemText(4, _translate("Form", "4"))
        self.comboBox_14.setItemText(0, _translate("Form", "0"))
        self.comboBox_14.setItemText(1, _translate("Form", "1"))
        self.comboBox_14.setItemText(2, _translate("Form", "2"))
        self.comboBox_14.setItemText(3, _translate("Form", "3"))
        self.comboBox_14.setItemText(4, _translate("Form", "4"))
        self.label_2.setText(_translate("Form", "1.มองเห็นภาพซ้อน ขณะที่มองจอคอมพิวเตอร์"))
        self.label_3.setText(_translate("Form", "2.มองเห็นภาพซ้อนเมื่อมองไปตามระยะทางหลังจากทำงานกับคอมพิวเตอร์"))
        self.label_4.setText(_translate("Form", "3.ความยากหรือช้าในการโฟกัสดวงตาจากจุดหนึ่งไปยังอีกไปยังอีกจุดหนึ่ง "))
        self.label_5.setText(_translate("Form", "4.ระคายเคืองตา"))
        self.label_6.setText(_translate("Form", "5.ตาแห้ง "))
        self.label_7.setText(_translate("Form", "6.ปวดตา "))
        self.label_8.setText(_translate("Form", "7.ปวดศีรษะ "))
        self.label_9.setText(_translate("Form", "8.เมื่อยตา"))
        self.label_10.setText(_translate("Form", "9.ไวต่อแสงจ้า "))
        self.label_11.setText(_translate("Form", "10.รู้สึกไม่สบายในตา "))
        self.label_12.setText(_translate("Form", "1.มีปัญหาการอ่านหนังสือ"))
        self.label_13.setText(_translate("Form", "2.มีปัญหาการขับขี่รถกลางคืน"))
        self.label_14.setText(_translate("Form", "3.มีปัญหาในการใช้งานคอมพิวเตอร์"))
        self.label_15.setText(_translate("Form", "4.มีปัญหาในการดูทีวี"))
        self.label_16.setText(_translate("Form", "แบบทดสอบเกี่ยวกับอาการล้าทางสายตา"))
        self.label_17.setText(_translate("Form", "ในสัปดาห์ที่ผ่านมา ขณะที่ท่านใช้คอมพิวเตอร์ มีอาการต่อไปนี้ หรือไม่ "))
        self.label_18.setText(_translate("Form", "แบบสอบถามประสบการณ์จากการใช้คอมพิวเตอร์"))
        self.label_19.setText(_translate("Form", "ในสัปดาห์ที่ผ่านมา ขณะที่ท่านใช้คอมพิวเตอร์ มีปัญหาต่อไปนี้เกิดขึ้นหรือไม่ "))
        self.label_20.setText(_translate("Form", "4 - ตลอดเวลา 3 - ส่วนใหญ่ 2 - ครึ่งหนึ่ง 1 - บางครั้ง 0 - ไม่เคย"))
        self.label_21.setText(_translate("Form", "4 - ตลอดเวลา 3 - ส่วนใหญ่ 2 - ครึ่งหนึ่ง 1 - บางครั้ง 0 - ไม่เคย"))
        self.label_22.setText(_translate("Form", "ข้อมูลทั่วไป"))
        self.label_23.setText(_translate("Form", "ชื่อ:"))
        self.label_24.setText(_translate("Form", "นามสกุล:"))
        self.label_25.setText(_translate("Form", "เพศ:"))
        self.comboBox_15.setItemText(0, _translate("Form", "ชาย"))
        self.comboBox_15.setItemText(1, _translate("Form", "หญิง"))
        self.label_26.setText(_translate("Form", "อายุ:"))
        self.label_27.setText(_translate("Form", "ในสัปดาห์ที่ผ่านมาท่านใช้คอมพิวเตอร์"))
        self.label_28.setText(_translate("Form", "ชั่วโมงต่อวัน "))
        self.label_29.setText(_translate("Form", "ท่านสวมใส่สิ่งต่อไปนี้ขณะใช้คอมพิวเตอร์ หรือไม่"))
        self.comboBox_16.setItemText(0, _translate("Form", "ไม่สวมใส่"))
        self.comboBox_16.setItemText(1, _translate("Form", "แว่นตา"))
        self.comboBox_16.setItemText(2, _translate("Form", "คอนเท็คเลนส์"))
        self.comboBox_16.setItemText(3, _translate("Form", "ใช้แว่นตาสวมทับคอนเท็คเลนส์"))
        self.label_30.setText(_translate("Form", "ท่านใช้น้ำตาเทียมในขณะที่ใช้คอมพิวเตอร์หรือไม่  "))
        self.comboBox_17.setItemText(0, _translate("Form", "ไม่ใช้"))
        self.comboBox_17.setItemText(1, _translate("Form", "ใช้"))
        self.label_31.setText(_translate("Form", "ท่านสูบบุหรี่หรือไม่"))
        self.comboBox_18.setItemText(0, _translate("Form", "ไม่สูบ"))
        self.comboBox_18.setItemText(1, _translate("Form", "สูบ"))
        self.pushButton_2.setText(_translate("Form", "Cancle"))

    def cvst(self):
        c1=int(self.comboBox.currenttext())
        c2=int(self.comboBox_2.currenttext())
        c3=int(self.comboBox_3.currenttext())
        c4=int(self.comboBox_4.currenttext())
        c5=int(self.comboBox_5.currenttext())
        c6=int(self.comboBox_6.currenttext())
        c7=int(self.comboBox_7.currenttext())
        c8=int(self.comboBox_8.currenttext())
        c9=int(self.comboBox_9.currenttext())
        c10=int(self.comboBox_10.currenttext())
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
